// The single source of truth for the package aliases.
//
// One glyph per workspace package, one table of who may import whom, and every
// tsconfig `paths` block in the repository is generated from the two. Run with
// `bun run aliases` after adding a package or a dependency edge; CI runs it with
// `--check` and fails if a tsconfig was edited by hand instead.
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'


export const GLYPH = {
  src:     'Δ', // the Next.js app shell: routes, API handlers, server-only helpers
  core:    'Ȼ', // shared domain configuration: ship registry, palettes, tuning, track metadata
  state:   'Ƨ', // client state on threejs-scene stores
  engine:  'Σ', // the client runtime: modules, HUD, netcode client, camera, FX, level meshes
  game:    'Ɠ', // composition roots: mountRace, mountBattle, mountHangar, mountCrashLab
  ui:      'Ʊ', // React components and hooks
  physics: 'Φ', // the simulation core: three + rapier, nothing else
  net:     'Ξ', // mode-agnostic netcode: clock, codec, interpolation, rewind
  race:    'Λ', // RaceSim, tracks, the race room
  battle:  'Ψ', // BattleSim, weapons, arena, the battle room
  data:    'Ð', // Drizzle over Neon; PGlite for tests
  server:  '§', // Colyseus boot
}

/** Direct dependencies. A package may import itself, these, and their closure. */
export const DEPS = {
  physics: [],
  net:     [],
  data:    [],
  race:    [ 'physics', 'net', 'data' ],
  battle:  [ 'physics', 'net', 'data' ],
  server:  [ 'race', 'battle', 'data', 'net' ],
  core:    [ 'physics', 'battle' ],
  state:   [ 'core', 'physics', 'battle', 'race' ],
  engine:  [ 'state', 'core', 'physics', 'net', 'race', 'battle' ],
  game:    [ 'engine', 'state', 'core', 'physics', 'net', 'race', 'battle' ],
  ui:      [ 'game', 'engine', 'state', 'core', 'physics', 'battle', 'race' ],
}

const ORDER    = [ 'physics', 'net', 'data', 'race', 'battle', 'core', 'state', 'engine', 'game', 'ui', 'server' ]
const root     = resolve(import.meta.dirname, '..')
const hasIndex = pkg => existsSync(resolve(root, `packages/${pkg}/src/index.ts`))

function closure (pkg, seen = []) {
  for (const dep of DEPS[pkg])
    if (!seen.includes(dep)) {
      seen.push(dep)
      closure(dep, seen)
    }
  return seen
}

function packageConfig (pkg) {
  const direct  = DEPS[pkg]
  const trans   = closure(pkg).filter(d => !direct.includes(d))
  const byOrder = (a, b) => ORDER.indexOf(a) - ORDER.indexOf(b)
  const paths   = {}
  for (const dep of [ pkg, ...direct.sort(byOrder), ...trans.sort(byOrder) ]) {
    const tsc = dep === pkg ? './src' : `../${dep}/src`
    const bun = `./packages/${dep}/src`
    if (hasIndex(dep))
      paths[GLYPH[dep]] = [ `${tsc}/index.ts`, `${bun}/index.ts` ]
    paths[`${GLYPH[dep]}*`] = [ `${tsc}/*`, `${bun}/*` ]
  }

  const types           = pkg === 'server' ? [ 'bun' ] : pkg === 'ui' ? [ 'node', 'react', 'react-dom' ] : [ 'node' ]
  const compilerOptions = { noEmit: true, types, paths }
  if (pkg === 'server')
    Object.assign(compilerOptions, { plugins: [], resolveJsonModule: true })

  const header = [
    '// Generated by `bun run aliases` from scripts/aliases.mjs — edit that, not this.',
    '//',
    '// `paths` IS the package boundary. Direct dependencies come first, then the',
    '// transitive closure tsc needs to type the files those pull in; nothing above',
    '// this package in the DAG appears, so an upward import fails `bun run typecheck`',
    '// instead of surfacing at boot.',
    '//',
    '// Every alias lists two candidates on purpose. tsc resolves a path relative to',
    '// THIS file; bun, when a tsconfig `extends` another, resolves it relative to the',
    '// root config instead (and `baseUrl`, the portable fix, is a TS 6 error). Each',
    '// tool skips the candidate that does not exist for it.',
    `// direct: ${direct.map(d => `${GLYPH[d]} ${d}`).join(', ') || 'none (leaf)'}`,
  ].join('\n')
  const config = {
    extends: '../../tsconfig.json',
    compilerOptions,
    include: [ 'src/**/*.ts', 'src/**/*.tsx', 'test/**/*.ts' ],
    exclude: [ 'node_modules' ],
  }
  return `${header}\n${JSON.stringify(config, null, 2)}\n`
}

function rootPaths () {
  const paths = { 'Δ*': [ './src/*' ]}
  for (const pkg of Object.keys(DEPS)) {
    if (hasIndex(pkg))
      paths[GLYPH[pkg]] = [ `./packages/${pkg}/src/index.ts` ]
    paths[`${GLYPH[pkg]}*`] = [ `./packages/${pkg}/src/*` ]
  }
  return paths
}

const check   = process.argv.includes('--check')
let drifted = false
function emit (file, content) {
  const path = resolve(root, file)
  if (check) {
    if (readFileSync(path, 'utf8') !== content) {
      console.error(`aliases: ${file} is out of date — run \`bun run aliases\``)
      drifted = true
    }
    return
  }
  writeFileSync(path, content)
}

for (const pkg of Object.keys(DEPS))
  emit(`packages/${pkg}/tsconfig.json`, packageConfig(pkg))

const rootFile                 = resolve(root, 'tsconfig.json')
const rootJson                 = JSON.parse(readFileSync(rootFile, 'utf8').replace(/^\s*\/\/.*$/gm, ''))
rootJson.compilerOptions.paths = rootPaths()
emit('tsconfig.json', `${JSON.stringify(rootJson, null, 2)}\n`)

if (check && drifted)
  process.exit(1)
if (!check)
  console.log(`aliases: wrote ${Object.keys(DEPS).length + 1} tsconfigs`)
